config/routes.rb
Rails.application.routes.draw do
  require "admin_constraint"
  mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new

  #########################################
  #==news url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    post "blogs", to: "blogs#create"
    get "/blogs/new", to: "blogs#new", as: :new_blog
    get "blogs/:title_for_slug/edit", to: "blogs#edit", as: "edit_blog"
    get "blogs/:title_for_slug", to: "blogs#show", as: "blog"
    patch "blogs/:title_for_slug", to: "blogs#update"
    put "blogs/:title_for_slug", to: "blogs#update"
    delete "blogs/:title_for_slug", to: "blogs#destroy"
  
  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end
  
  root 'home#index'

  match '/about-us'              =>        'home#about',              via: [:get],            :as => 'about'
  match '/gallery'              =>        'home#gallery',              via: [:get],            :as => 'gallery'
  match '/services'              =>        'home#services',              via: [:get],            :as => 'services'
  match '/contact'              =>        'home#contact',              via: [:get],            :as => 'contact'

  match '/decks'              =>        'galleries#decks',              via: [:get],            :as => 'decks'
  match '/pools'              =>        'galleries#pools',              via: [:get],            :as => 'pools'
  match '/hillside-decks'              =>        'galleries#hillside_decks',              via: [:get],            :as => 'hillside_decks'
  match '/railing'              =>        'galleries#railing',              via: [:get],            :as => 'railing'
  match '/hardscape'              =>        'galleries#hardscape',              via: [:get],            :as => 'hardscapes'
  match '/fences'              =>        'galleries#fences',              via: [:get],            :as => 'fences'
  match '/patio-covers'              =>        'galleries#patio_covers',              via: [:get],            :as => 'patio_covers'
  match '/commercial-decks'              =>        'galleries#commercial_decks',              via: [:get],            :as => 'commercial_decks'
  match '/other-projects'              =>        'galleries#other_projects',              via: [:get],            :as => 'other_projects'
  
  match '/ipe-decks'              =>        'galleries#ipe_decks',              via: [:get],            :as => 'ipe_decks'
  match '/azek-decks'              =>        'galleries#azek_decks',              via: [:get],            :as => 'azek_decks'
  match '/trex-decks'              =>        'galleries#trex_decks',              via: [:get],            :as => 'trex_decks'
  match '/mangaris-decks'              =>        'galleries#mangaris_decks',              via: [:get],            :as => 'mangaris_decks'

  match '/pools-new'              =>        'galleries#pools_new',              via: [:get],            :as => 'pools_new'
  match '/pools-remodel'              =>        'galleries#pools_remodel',              via: [:get],            :as => 'pools_remodel'

  match '/railing-glass'              =>        'galleries#railing_glass',              via: [:get],            :as => 'railing_glass'
  match '/railing-cable'              =>        'galleries#railing_cable',              via: [:get],            :as => 'railing_cable'
  match '/railing-other'              =>        'galleries#railing_other',              via: [:get],            :as => 'railing_other'

  # match '/deck-railing'              =>        'galleries#deck_railing',              via: [:get],            :as => 'deck_railing'
  # match '/fences-and-railing'              =>        'galleries#fences_and_railing',              via: [:get],            :as => 'fences_and_railing'
  # match '/patio'              =>        'galleries#patio',              via: [:get],            :as => 'patio'


  match "/contacts"              =>        "contacts#create",              via: [:post]
  
  match "/new-image"              =>        "galleries#new",              via: [:get],    :as => 'new_image'
  match "/create-image"              =>        "galleries#create",              via: [:post]
  match "/update-image"              =>        "galleries#update",              via: [:patch]
  match "/delete-image"             =>        "galleries#destroy",              via: [:delete], :as => 'delete_image'
end

app/models/blog.rb
class Blog < ApplicationRecord

  validates :title, uniqueness: {case_sensitive: false}

  before_save :title_url_it
  before_save :remove_img

  has_many :images, as: :imageable, :class_name => "Blog::Asset", dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  
  #This is for SEO purposes, you want the url to be the title of the blog instead of its ID
  def title_url_it
    self.title_for_slug = title.downcase.squish.parameterize("-")
  end

  def remove_img
    nokogiri_html_document =  Nokogiri::HTML(self.content) #heroku does not like tmp directory
    nokogiri_html_document.search('img').each do |img|
      img.remove
    end
    self.content_index = nokogiri_html_document
    #note that if you call self.save here, you might run into infinite loops (stack level too deep), even for after_save, after_create and after_update callbacks
  end

end

app/models/blog/asset.rb
class Blog::Asset < Image
  
  ##============================================================##
  ## Paperclip Interpolates
  ##============================================================##
  Paperclip.interpolates :imageable_type do |attachment, style|
    attachment.instance.imageable_type.downcase
  end

  Paperclip.interpolates :imageable_id do |attachment, style|
    attachment.instance.imageable_id
  end

  has_attached_file :pic,
    :path => "#{Rails.env}/:imageable_type/:imageable_id/:style/:filename",
    :styles => { 
      :medium => ["600x400>", :jpg], 
      :large => ["1200x800>", :jpg]
    },
    :convert_options => {
     # :medium => "-quality 80 -interlace Plane",
     # :small => "-quality 80 -interlace Plane",
     # :thumb => "-quality 80 -interlace Plane",
     # :facebook_meta_tag => "-quality 80 -interlace Plane" 
    },
    :s3_headers => { 'Cache-Control' => 'max-age=315576000', 'Expires' => 10.years.from_now.httpdate }

  validates_attachment :pic, content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] }, size: { in: 0..3000.kilobytes }, presence: true

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  def index
    @blogs = Blog.all.order("id ASC")
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to blog_path(@blog.title_for_slug), notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blog_path(@blog.title_for_slug), notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private

    def set_blog
      @blog = Blog.find_by(title_for_slug: params[:title_for_slug])
    end

    def blog_params
      params.require(:blog).permit(:title, :content, :content_index, :title_for_slug, :main_image, :pubdate, :meta_description, :meta_keywords, images_attributes: [:id, :pic, :name, :_destroy])
    end

end

app/views/blogs/_form.html.erb
<%= form_for(blog, :url => (blog.new_record? ? blogs_url : blog_path(blog.title_for_slug)), :html => { :multipart => true }) do |f| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.cktext_area :content, class: "form-control ckeditor" %>
  </div>

  <div class="form-group">
    <%= f.label :meta_description %>
    <%= f.text_field :meta_description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :meta_keywords %>
    <%= f.text_field :meta_keywords, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.fields_for :images, @blog.images.build do |t| %>
      <%= t.label :pic, "Main Image (1200x800 for consistency)" %> <br>

      <% if @blog.images.exists? %>
        <%= image_tag @blog.images[0].pic.url(:medium), id: 'current_image', class: 'mb15' %><br/>
      <% else %>
        <img id="current_image" class="mb5" src="#" alt="">
      <% end %>

      <%= t.file_field :pic, style: "padding: 4px;" %>  
      <%#= In order to make multiple file uploads you'd have to do it like you did in oldpalm, add multiple true, and loop through params[:pic] in your controller and create images that way %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :pubdate %><br>
    <%= f.date_field :pubdate, value: Date.today, class:'form-control', required: true %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: "form-control btn btn-primary" %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<% provide(:title, 'GCG Ground News') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">

      <h1>Editing Blog</h1>

      <%= render 'form', blog: @blog %>

      <div class="mt15 mb30">
        <%= link_to '< Back', blogs_path, class: 'btn btn-default' %>
        <%= link_to 'Show Blog', blog_path(@blog.title_for_slug), class: 'btn btn-default' %> 
      </div>

    </div>
  </div>
</div>

app/views/blogs/index.html.erb
<% provide(:title, 'Blogs | La Decks') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<!-- <section class="hero-about"></section> -->

<section>

  <div class="container">
  <%= link_to 'New Blog', new_blog_path, class:"btn btn-primary mb30" if current_user.try(:admin?)%>

    <div class="row">
    
      <% @blogs.each do |blog| %>
        <div class="col-md-6 mb40">
          <h2 class="mb20"><%= link_to blog.title, blog_path(blog.title_for_slug), class: "textcolor-primary btnblogtitle" %></h2>
          <%= link_to blog_path(blog.title_for_slug) do %> 
            <%= image_tag(blog.images[0].pic.url(:medium), class:'img-responsive mb20') if blog.images.present?%>
          <% end %>
          <p><%= HTML_Truncator.truncate(blog.content_index, 20).html_safe %></p>
          <div class="mt20">
            <%= link_to 'Read More', blog_path(blog.title_for_slug), class:"btn btn-default btnblogindex" %>
            <%= link_to 'Edit', edit_blog_path(blog.title_for_slug), class:"btn btn-default btnblogindex" if current_user.try(:admin?)%>
            <%= link_to 'Destroy', blog_path(blog.title_for_slug), class:"btn btn-default btnblogindex", method: :delete, data: { confirm: 'Are you sure?' } if current_user.try(:admin?) %>
          </div>
        </div>
      <% end %>

    </div>

  </div>
  
</section>

app/views/blogs/new.html.erb
<% provide(:title, 'GCG Ground News') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
  <meta name="turbolinks-cache-control" content="no-cache">
<% end %>

<div class="container">
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <h1>New Blog</h1>

      <%= render 'form', blog: @blog %>

      <div class="mt30 mb30">
         <%= link_to 'Back', blogs_path, class: 'btn btn-default' %>
      </div>
     
    </div>
  </div>
</div>

app/views/blogs/show.html.erb
<% provide(:title, "Blog | #{@blog.title} | La Decks") %>
<% content_for :head do%>
  <meta name="description" content="<%= @blog.meta_description %>">
  <meta name="keywords" content="<%= @blog.meta_keywords %>">
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
      <h1 class="mt70 mb0"><%= @blog.title %></h1>
      <p class="small mb30"><%= @blog.pubdate.strftime("%B %d, %Y") if @blog.pubdate.present? %></p>

      <%= image_tag(@blog.images[0].pic.url(:large), class:'img-responsive') if @blog.images.present? %>
      <p class="mt30"><%= @blog.content.html_safe %></p>
      <div class="mt30 mb60">
        <%= link_to 'Back', blogs_path, class: "btn btn-default btnblogindex" %>
        <%= link_to 'Edit', edit_blog_path(@blog.title_for_slug), class: "btn btn-default btnblogindex" if current_user.try(:admin?) %>
      </div>
    </div>
  </div>
</div>