config/routes.rb
Rails.application.routes.draw do
  require "admin_constraint"
  mount Ckeditor::Engine => "/ckeditor", constraints: AdminConstraint.new

  #########################################
  #==news url for blog model
  #########################################
    get "/blogs", to: "blogs#index", as: :blogs
    post "blogs", to: "blogs#create"
    get "/blogs/new", to: "blogs#new", as: :new_blog
    get "blogs/:title_for_slug/edit", to: "blogs#edit", as: "edit_blog"
    get "blogs/:title_for_slug", to: "blogs#show", as: "blog"
    patch "blogs/:title_for_slug", to: "blogs#update"
    put "blogs/:title_for_slug", to: "blogs#update"
    delete "blogs/:title_for_slug", to: "blogs#destroy"
  
  devise_scope :user do
    get "/users/sign_up",  :to => "devise/sessions#new"
  end
  
  devise_for :users

  devise_scope :user do 
    get "/admin" => "devise/sessions#new" 
  end
  
  root 'home#index'

  match '/about-us'              =>        'home#about',              via: [:get],            :as => 'about'
  match '/gallery'              =>        'home#gallery',              via: [:get],            :as => 'gallery'
  match '/services'              =>        'home#services',              via: [:get],            :as => 'services'
  match '/contact'              =>        'home#contact',              via: [:get],            :as => 'contact'

  match '/decks'              =>        'galleries#decks',              via: [:get],            :as => 'decks'
  match '/pools'              =>        'galleries#pools',              via: [:get],            :as => 'pools'
  match '/hillside-decks'              =>        'galleries#hillside_decks',              via: [:get],            :as => 'hillside_decks'
  match '/railing'              =>        'galleries#railing',              via: [:get],            :as => 'railing'
  match '/hardscape'              =>        'galleries#hardscape',              via: [:get],            :as => 'hardscapes'
  match '/fences'              =>        'galleries#fences',              via: [:get],            :as => 'fences'
  match '/patio-covers'              =>        'galleries#patio_covers',              via: [:get],            :as => 'patio_covers'
  match '/commercial-decks'              =>        'galleries#commercial_decks',              via: [:get],            :as => 'commercial_decks'
  match '/other-projects'              =>        'galleries#other_projects',              via: [:get],            :as => 'other_projects'
  
  match '/ipe-decks'              =>        'galleries#ipe_decks',              via: [:get],            :as => 'ipe_decks'
  match '/azek-decks'              =>        'galleries#azek_decks',              via: [:get],            :as => 'azek_decks'
  match '/trex-decks'              =>        'galleries#trex_decks',              via: [:get],            :as => 'trex_decks'
  match '/mangaris-decks'              =>        'galleries#mangaris_decks',              via: [:get],            :as => 'mangaris_decks'

  match '/pools-new'              =>        'galleries#pools_new',              via: [:get],            :as => 'pools_new'
  match '/pools-remodel'              =>        'galleries#pools_remodel',              via: [:get],            :as => 'pools_remodel'

  match '/railing-glass'              =>        'galleries#railing_glass',              via: [:get],            :as => 'railing_glass'
  match '/railing-cable'              =>        'galleries#railing_cable',              via: [:get],            :as => 'railing_cable'
  match '/railing-other'              =>        'galleries#railing_other',              via: [:get],            :as => 'railing_other'

  # match '/deck-railing'              =>        'galleries#deck_railing',              via: [:get],            :as => 'deck_railing'
  # match '/fences-and-railing'              =>        'galleries#fences_and_railing',              via: [:get],            :as => 'fences_and_railing'
  # match '/patio'              =>        'galleries#patio',              via: [:get],            :as => 'patio'


  match "/contacts"              =>        "contacts#create",              via: [:post]
  
  match "/new-image"              =>        "galleries#new",              via: [:get],    :as => 'new_image'
  match "/create-image"              =>        "galleries#create",              via: [:post]
  match "/update-image"              =>        "galleries#update",              via: [:patch]
  match "/delete-image"             =>        "galleries#destroy",              via: [:delete], :as => 'delete_image'
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
   
  def decks
    @deck = Deck.where(name: "decks").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def pools
    @deck = Deck.where(name: "pools").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def hillside_decks
    @deck = Deck.where(name: "hillside-decks").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def railing
    @deck = Deck.where(name: "railing").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def hardscape
    @deck = Deck.where(name: "hardscape").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def fences
    @deck = Deck.where(name: "fences").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def patio_covers
    @deck = Deck.where(name: "patio-covers").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def commercial_decks
    @deck = Deck.where(name: "commercial-decks").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def other_projects
    @deck = Deck.where(name: "other-projects").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end



  def ipe_decks
    @deck = Deck.where(name: "ipe-decks").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def azek_decks
    @deck = Deck.where(name: "azek-decks").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def trex_decks
    @deck = Deck.where(name: "trex-decks").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def mangaris_decks
    @deck = Deck.where(name: "mangaris-decks").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end



  def pools_new
    @deck = Deck.where(name: "pools-new").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def pools_remodel
    @deck = Deck.where(name: "pools-remodel").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end


  def railing_glass
    @deck = Deck.where(name: "railing-glass").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def railing_cable
    @deck = Deck.where(name: "railing-cable").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  def railing_other
    @deck = Deck.where(name: "railing-other").first
    @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  end

  # def deck_railing
  #   @deck = Deck.where(name: "deck-railing").first
  #   @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  # end

  # def fences_and_railing
  #   @deck = Deck.where(name: "fences-and-railing").first
  #   @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  # end
  
  # def patio
  #   @deck = Deck.where(name: "patio").first
  #   @images = Image.where(imageable_type: "Deck", imageable_id: @deck.id)
  # end




  def new
    @deck = Deck.where(name: params[:deckname]).first
  end

  def create
    @deck = Deck.where(name: params[:deckname]).first
    params[:pics].each do |picture|
      @deck.images.create(pic: picture)
    end if params[:pics].present? 
    redirect_to root_path + "/#{params[:deckname]}"
  end

  def update
    @deck = Deck.where(name: params[:deckname]).first
    params[:pics].each do |picture|
      @deck.images.create(pic: picture)
    end if params[:pics].present? 
    redirect_to "/#{@deck.name}"
  end

  def destroy
    deck = Deck.find(params[:mydeck].to_i)
    image = deck.images.find(params[:myimage].to_i)
    image.destroy
    redirect_to :back, notice: 'Image was successfully destroyed.'
  end

  private


  def deck_params
    params.require(:deck).permit(:name, images_attributes: [:id, :pic, :name, :_destroy])
  end


end

app/views/galleries/azek_decks.html.erb
<% provide(:title, 'Gallery | Azek Decks in the Los Angeles Area | La Decks') %>
<% content_for :head do%>
  <meta name="description" content="Azek decks are a beautiful, long-lasting alternative to wood. No more annual staining and sealing. Contact us today for your LA Azek deck design estimate.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-azek-decks"></section>
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Azek Decks <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) if current_user.try(:admin?)%></h1>
        <p>Azek decks are regarded for being one of the most beautiful and long-lasting wood alternatives available. Though this product looks and feels just like real wood, it is actually a capped polymer material expertly engineered to stand the test of time. When you choose Azek as your decking material, annual staining and sealing and sealing is a thing of the past, a fact which will save you both time and money over the years. This material is also available in a variety of colors, one of which is sure to mesh with your style. As a testament to its durability, Azek decks are backed by a 30-year warranty.</p>
      </div>
    </div>
  </div>
</section>


<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>

app/views/galleries/commercial_decks.html.erb
<% provide(:title, 'Commercial |Commercial Decks Builder in Los Angeles | LA Decks') %>
<% content_for :head do%>
  <meta name="description" content="Browse our gallery of commercial decks that we have designed and built around Los Angeles. Contact us now for a free estimate.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-commercial-decks"></section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Commercial Decks <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) if current_user.try(:admin?)%></h1>
        <!-- <p>Fences are not only decorative, but also an important safety component in any backyard. Before developing a design for your fence, we work closely with you to understand your goals for the project. Whether you’re looking to achieve more privacy, keep your family safe, or simply create a more aesthetically pleasing outdoor space, we can help you achieve it. We carefully develop of a structure that meets your goals, while enhancing the look of your backyard in the process. Our team uses the highest quality of materials to construct every fence, and our designs meet and exceed all safety standards.</p> -->
      </div>
    </div>
  </div>
</section>


<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>

app/views/galleries/deck_railing.html.erb
<% provide(:title, 'Gallery | Deck Railings in the Los Angeles Area | La Decks') %>
<% content_for :head do%>
  <meta name="description" content="Deck railing are a necessity, but they can also be beautiful. We provide glass, cable, and other deck railing options in and around the Los Angeles area.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-deck-railing"></section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Deck Railings <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) if current_user.try(:admin?)%></h1>
        <p>Deck railings are a necessity, but that doesn’t mean they can’t also be beautiful. Railings are essential for keeping you, your family and your guests safe when enjoying outdoor living on your new backyard deck. Our designs are crafted to accompany your deck with your needs and preferences in mind, offering a range of both modern and traditional styles. We can advise you on the best option for your situation, whether that be a glass, cable or wood railing. The end result is a piece that not only perfectly complements your deck, but your lifestyle as well.</p>
      </div>
    </div>
  </div>
</section>


<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>

app/views/galleries/decks.html.erb
<% provide(:title, 'Gallery | Decks in the Los Angeles Area | La Decks') %>
<% content_for :head do%>
  <meta name="description" content="Enhance your outdoor LA living with a customized backyard deck built to your lifestyle & needs. Hillside, ground, or rooftop decks are our specialties.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-decks"></section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Decks</h1>
        <p>At L.A. Decks, we believe the best way to enhance outdoor living is with a customized deck, designed with your needs and lifestyle in mind. Though hillside decks are our specialty, our ground level and rooftop decks are equally impressive. We offer free on-site estimates, so that we can truly get a feel for your outdoor space before heading to the drawing board. When the time comes to build, our licensed professionals use the highest quality materials for every project. This ensures your deck is not only built to enjoy, but to last.</p>
      </div>
    </div>
  </div>
</section>

<section class="pt0">
  <div class="container">
    <div class="row pb2">
      <div class="col-sm-6 col-xs-12 pl1 pr1">
        <div class="gallery-item">
          <img src="https://s3-us-west-1.amazonaws.com/la-decks/general/la-decks-decks-azek-decks.jpg" alt="" class="">
          <div class="cover-item-gallery">
            <a href="/azek-decks">
              <span class="myclass azek">Azek Decks</span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-xs-12 pl1 pr1">
        <div class="gallery-item">
          <img src="https://s3-us-west-1.amazonaws.com/la-decks/general/la-decks-decks-ipe-decks.jpg" alt="" class="">
          <div class="cover-item-gallery">
            <a href="/ipe-decks">
              <span class="myclass ipe">IPE Decks</span>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="row pb2">
      <div class="col-sm-6 col-xs-12 pl1 pr1">
        <div class="gallery-item">
          <img src="https://s3-us-west-1.amazonaws.com/la-decks/general/la-decks-decks-mangaris-decks.png" alt="" class="">
          <div class="cover-item-gallery">
            <a href="/mangaris-decks">
              <span class="myclass mangaris">Mangaris Decks</span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-xs-12 pl1 pr1">
        <div class="gallery-item">
          <img src="https://s3-us-west-1.amazonaws.com/la-decks/general/la-decks-decks-trex-decks.jpg" alt="" class="">
          <div class="cover-item-gallery">
            <a href="/trex-decks">
              <span class="myclass trex">Trex Decks</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<%= render 'layouts/service_contact_form' %>

app/views/galleries/fences.html.erb
<% provide(:title, 'Gallery | Decks in the Los Angeles Area | La Decks') %>
<% content_for :head do%>
  <!-- <meta name="description" content="home description"> -->
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-fences"></section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Fences <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) if current_user.try(:admin?)%></h1>
        <p>Fences are not only decorative, but also an important safety component in any backyard. Before developing a design for your fence, we work closely with you to understand your goals for the project. Whether you’re looking to achieve more privacy, keep your family safe, or simply create a more aesthetically pleasing outdoor space, we can help you achieve it. We carefully develop of a structure that meets your goals, while enhancing the look of your backyard in the process. Our team uses the highest quality of materials to construct every fence, and our designs meet and exceed all safety standards.</p>
      </div>
    </div>
  </div>
</section>


<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>

app/views/galleries/hardscape.html.erb
<% provide(:title, ' Hardscape | Hardscape Designer and Builder in LA | LA Decks') %>
<% content_for :head do%>
  <meta name="description" content="Rely on our vision and skill to design and install an elegant hardscape to your LA home or backyard. Over 20 years of experience. Free estimates available.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-hardscapes"></section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Hardscapes <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) if current_user.try(:admin?)%></h1>
        <p>Designing and installing elegant hardscapes takes more than just creativity; it requires vision and skill that can only come from years of experience. Our team has been masterfully executing customized hardscapes for nearly 20 years, and we’re here to help with all of your hardscaping needs. Whether designing a beautiful patio, installing a paved path or driveway, building a charming fireplace, or constructing a wall that completes your outdoor space, quality is our guarantee. We use high quality materials and incorporate proven installation techniques to ensure your expectations are always exceeded.</p>
      </div>
    </div>
  </div>
</section>


<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>

app/views/galleries/new.html.erb
<div class="container mt60 mb30">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @deck, url: '/update-image', html: {multipart: true} do |f| %>
        <% if @deck.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(deck.errors.count, "error") %> prohibited this blog from being saved:</h2>

            <ul>
            <% @deck.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>


        <div class="form-group">
          <%= hidden_field_tag :deckname, @deck.name %>
        </div>

        <div class="form-group mt30">
          <%= f.label :pic, "Upload Images" %><br>
          <%= file_field_tag 'pics[]', multiple: true %>
        </div>

        <div class="form-group">
          <%= f.button "Submit", class: "form-control btn btn-primary", data: {disable_with: "<i class='fa fa-refresh fa-spin'></i> Uploading images..."} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/galleries/patio_covers.html.erb
<% provide(:title, 'Gallery | Patio covers in the Los Angeles Area | La Decks') %>
<% content_for :head do%>
  <meta name="description" content="Beautiful, high-quality, and functional pergolas and patio covers in the LA area by LA Decks. Get ready to entertain with a free estimate today.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-patio-cover"></section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Patio Covers <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) if current_user.try(:admin?)%></h1>
        <p>Our pergolas and patio covers offer an ideal combination of beauty, quality and functionality. Pergolas differ from traditional coverings in that they do not have a roof, but rather a series of posts. The sun is always shining in Southern California, and the shade provided by these elegant coverings is a welcome relief. Whether an addition to your deck or a standalone feature in your backyard, a well designed pergola is the perfect way to make your outdoor space shine and set the perfect stage for entertaining.</p>
      </div>
    </div>
  </div>
</section>


<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>

app/views/galleries/pools_new.html.erb
<% provide(:title, 'Gallery | New Pool Builder in LA | LA Decks') %>
<% content_for :head do%>
  <meta name="description" content="Browse our gallery of new pool designs and builds from around the LA area. Contact us today to receive your free quote on your new pool design.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-pools-new"></section>

<% if current_user.try(:admin?) %>
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Pool-New <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) %></h1>
      </div>
    </div>
  </div>
</section>
<% end %>


<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>

app/views/galleries/pools_remodel.html.erb
<% provide(:title, 'Gallery | Remodeled Pool Builder in LA | LA Decks') %>
<% content_for :head do%>
  <meta name="description" content="Browse our gallery of remodeled pool projects and builds from around the LA area. Contact us today to receive your free quote on your remodeled pool design.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-pools-remodel"></section>


<% if current_user.try(:admin?) %>
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Pool-Remodel <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) %></h1>
      </div>
    </div>
  </div>
</section>
<% end %>


<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>

app/views/galleries/railing_cable.html.erb
<% provide(:title, 'Gallery | Cable Railings in the Los Angeles Area | La Decks') %>
<% content_for :head do%>
  <meta name="description" content="Browse our gallery of backyard cable railings from around the Los Angeles area. Contact us today for a free quote.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-railing-cable"></section>

<% if current_user.try(:admin?) %>
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Railing-Cable <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) %></h1>
      </div>
    </div>
  </div>
</section>
<% end %>

<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>

app/views/galleries/railing_other.html.erb
<% provide(:title, 'Gallery | Other Railings in the Los Angeles Area | La Decks') %>
<% content_for :head do%>
  <meta name="description" content="Browse our gallery of other backyard railings from around the Los Angeles area. Contact us today for a free quote.">
  <!-- <meta name="keywords" content="home keywords"> -->
  <!-- <link rel="canonical" href="http://www.mysite.com/mypage/"/> -->
<% end %>

<section class="hero-railing-other"></section>

<% if current_user.try(:admin?) %>
<section>
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>Railing-Other <%= link_to "(Add Image)", new_image_path(deckname: @deck.name) %></h1>
      </div>
    </div>
  </div>
</section>
<% end %>


<section class="images pt0">
  <div class="grid">
    <div class="grid-sizer"></div>
    <% @deck.images.each do |image| %>
      <div class="grid-item">
        <%= image_tag (image.pic.url(:original)) %>
        <% if current_user.try(:admin?) %><p><%= link_to "delete image", delete_image_path(myimage: image.id, mydeck: @deck.id), method: :delete, data: { confirm: 'Are you sure?' } %></p><br><% end %>
      </div>
    <% end if @deck.images.present?%>
  </div>
</section>

<%= render 'layouts/service_contact_form' %>